apiVersion: apps/v1
kind: Deployment
metadata:
  name: deduct-fe-deployment
  labels:
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deduct-fe
  template:
    metadata:
      labels:
        app: deduct-fe
    spec:
      containers:
      - name: deduct-fe-pod
        image: public.ecr.aws/t9g0p6z9/deduct-image:latest
        ports:
        - containerPort: 3000

